[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
rp-pico = "0.8"
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2.7"
panic-halt = "0.2"
cortex-m-semihosting = "0.5"

# Cargo build scripts and/or proc-macros
rp2040-boot2 = "0.3"
